---
title: "Data Question 4 Extension: Exploration of TN Academic and Income Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: lumen
    social: menu
    source: embed
---

<style>                     
.navbar {
  background-color:blue;
  border-color:red;
}
.navbar-brand {
color:white!important;
}

</style>   


```{r setup, include=FALSE, message = FALSE, warning = FALSE, echo=FALSE}
library("flexdashboard")
library("tidyverse")
library("readxl")
library("dplyr")
library("magrittr")
library("ggplot2")
library("GGally")
library("broom")
library("plyr")
library("ggmap")
library("maps")
library("mapdata")
library("rgeos")
library("maptools")
library("sp")
library("raster")
library("rgdal")
library("sf")
library("broom")
library("stringr")

irs <- read.csv("data/irs_avg.csv")
edu_raw <- read.csv("data/achievement_profile_data_with_CORE.csv")
merged_irs <- read.csv("data/merged.csv")
edu_act <- read.csv("data/edu_act.csv")
total_sal_2014 <- read.csv("data/total_sal_2014.csv")
usa <- map_data("usa")
states <- map_data("state")
tn_df <- subset(states, region == "tennessee")
counties <- map_data("county")
tn_counties <- subset(counties, region == "tennessee")
```


Column{data-width=600}{.tabset}
-----------------------------------------------------------------------

### Correlation Matrix of Core Education Data

* Data gathered from the TN department of Education from the [the 2014 - 2015 school year](https://www.tn.gov/education/data/data-downloads.html) seen within the correlation matrix below. 

* A consistant positive correlation between academic attributes can be seen.  

* ACT composite scores are noticably negatively correlated with percent absent, economically disadvantaged, and suspended. 

```{r echo=FALSE, fig.width=15, fig.height=10}
edu_2 <- dplyr::select(edu_raw, system_name,BioI,Chemistry,ELA,EngI,EngII,EngIII,AlgI,AlgII,Math,Science,ACT_Composite,Graduation,Pct_Native_American,Pct_SWD,
                Pct_Black,Pct_Hispanic,Pct_EL,Pct_ED,Pct_BHN,Pct_Chronically_Absent,
                Pct_Suspended,Pct_Expelled,Per_Pupil_Expenditures,Enrollment
)
ggcorr(edu_2)

```


### Correlation Matrix of Averaged IRS Data

* Data gathered from the IRS from the [2011 - 2015](https://www.irs.gov/statistics/soi-tax-stats-individual-income-tax-statistics-zip-code-data-soi) can been seen within the correlation matrix below. These metrics ere averaged in order to not take population into account.

* A consistant positive correlation between avergaed amounts coming into the household and avg AGI.  

* Conversely, earned income credits are clearly negatively correlated with the AGI attributes.  

```{r echo=FALSE, fig.width=15, fig.height=10}

ggcorr(irs)


```


Column {data-width=600}{.tabset}
-----------------------------------------------------------------------

### Per Pupil Expenditure

```{r echo=FALSE, fig.width=15, fig.height=10}

tn_base <- ggplot(data = tn_df, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")

#I need to be able to merge these two to create the ggmap

core <- read.csv("data/merged_county.csv")
colnames(core)[2] <- "subregion" #renaming to match
core[[2]] <- tolower(core[[2]]) #changing to all lowercase

#removing 'county' from the column

core$subregion <- gsub(" county$", "", core$subregion)
tn_counties$subregion <- replace(tn_counties$subregion, tn_counties$subregion=="de kalb", "dekalb")

#merging the two dataframes together with nnner_join

tn_core <- inner_join(tn_counties, core, by = "subregion")

#Attempting to plot

ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
)

tn_per_pupil <- tn_base + 
  geom_polygon(data = tn_core, aes(fill = Per_Pupil_Expenditures), color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes

tn_per_pupil

```

### Graduation Rates

```{r echo=FALSE, fig.width=15, fig.height=10}
tn_graduation <- tn_base + 
  geom_polygon(data = tn_core, aes(fill = Graduation), color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes

tn_graduation

```

### Dropout Rate

```{r echo=FALSE, fig.width=15, fig.height=10}
tn_dropout <- tn_base + 
  geom_polygon(data = tn_core, aes(fill = Dropout), color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes

tn_dropout
```

### Percentage of Black, Hispanic, and Native American 

```{r echo=FALSE, fig.width=15, fig.height=10}
tn_per_BHN <- tn_base + 
  geom_polygon(data = tn_core, aes(fill = Pct_BHN), color = "white") +
  geom_polygon(color = "black", fill = NA) +
  theme_bw() +
  ditch_the_axes

tn_per_BHN
```